bills/urls.py
from django.urls import path
from bills import views

app_name = 'bills'
urlpatterns = [
    # 請求一覧
    path('list/', views.get_bill_list, name='list'),   # 一覧
]

customers/urls.py
from django.urls import path
from customers import views

app_name = 'customers'
urlpatterns = [
    # 顧客
    path('list/', views.get_customer_list, name='list'),   # 一覧
    path('add/', views.customer_edit, name='add'),  # 登録
    path('edit/<int:customer_id>/', views.customer_edit, name='edit'),  # 修正
]

sample_app/urls.py
from django.contrib import admin
from django.urls import path, include
from templates import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.index_template, name='index'),
    path('bills/', include('bills.urls')),
    path('customers/', include('customers.urls')),
    path('lessons/', include('lessons.urls')),
    path('reports/', include('reports.urls')),
]

customers/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Customer(models.Model):
    """
    顧客
    """
    MALE_STRING = '男性'
    FEMALE_STRING = '女性'
    GENDER = (
        (MALE_STRING, MALE_STRING),
        (FEMALE_STRING, FEMALE_STRING),
    )

    name = models.CharField(
        verbose_name='名前',
        max_length=30,
    )
    gender = models.CharField(
        verbose_name='性別',
        max_length=10,
        choices=GENDER,
    )
    age = models.PositiveSmallIntegerField(
        verbose_name='年齢',
        validators=[MinValueValidator(0), MaxValueValidator(150),])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

customers/forms.py
from django.forms import ModelForm
from customers.models import Customer


class CustomerForm(ModelForm):
    """
    顧客フォーム
    """
    class Meta:
        model = Customer
        fields = (
            'name',
            'gender',
            'age',
        )

customers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from customers.models import Customer
from customers.forms import CustomerForm


def get_customer_list(request):
    """
    顧客一覧を取得する
    """

    customers = Customer.objects.all().order_by('id')
    return render(request,
                  'customers/list.html',
                  {'customers': customers},
                  )

def customer_edit(request, customer_id=None):
    """
    顧客を新規作成/編集する
    """

    if customer_id:
        customer = get_object_or_404(Customer, pk=customer_id)
    else:
        customer = Customer()

    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.save()
            return redirect('customers:list')
    else:
        form = CustomerForm(instance=customer)

    return render(
        request,
        'customers/edit.html',
        dict(form=form, customer_id=customer_id)
    )

customers/templates/customers/edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}
    {% if customer_id %}
    顧客編集
    {% else %}
    顧客追加
    {% endif %}
{% endblock %}

{% block body %}
    {% if customer_id %}
    <h4 class="mt-4 mb-5 border-bottom">顧客編集</h4>
    <form action="{% url 'customers:edit' customer_id=customer_id %}" method="post">
    {% else %}
    <h4 class="mt-4 mb-5 border-bottom">顧客追加</h4>
    <form action="{% url 'customers:add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
{% endblock %}

customers/templates/customers/list.html
{% extends "base.html" %}

{% block title %}
顧客一覧
{% endblock %}

{% block body %}
<h4 class="mt-4 border-bottom">顧客一覧</h4>
<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">名前</th>
      <th scope="col">性別</th>
      <th scope="col">年齢</th>
    </tr>
  </thead>
  <tbody>
    {% for customer in customers %}
    <tr>
      <th scope="row">{{ customer.id }}</th>
      <td>{{ customer.name }}</td>
      <td>{{ customer.gender }}</td>
      <td>{{ customer.age }}</td>
      <td>
        <a href="{% url 'customers:edit' customer_id=customer.id %}" class="btn btn-outline-primary btn-sm">編集</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'customers:add' %}" class="btn btn-primary btn-sm my-3">新規追加</a>
{% endblock %}