bills/urls.py
from django.urls import path
from bills import views

app_name = 'bills'
urlpatterns = [
    # 請求一覧
    path('list/', views.get_bill_list, name='list'),   # 一覧
]

customers/urls.py
from django.urls import path
from customers import views

app_name = 'customers'
urlpatterns = [
    # 顧客
    path('list/', views.get_customer_list, name='list'),   # 一覧
    path('add/', views.customer_edit, name='add'),  # 登録
    path('edit/<int:customer_id>/', views.customer_edit, name='edit'),  # 修正
]

lessons/urls.py
from django.urls import path
from lessons import views

app_name = 'lessons'
urlpatterns = [
    # レッスン
    path('list/', views.get_lesson_history_list, name='history_list'),   # 一覧
    path('genre_list/', views.get_lesson_genre_list, name='genre_list'),   # 一覧
    path('add/', views.lesson_history_edit, name='history_add'),  # 登録
    path('genre_add/', views.lesson_genre_edit, name='genre_add'),  # 登録
    path('edit/<int:history_id>/', views.lesson_history_edit, name='history_edit'),  # 修正
    path('genre_edit/<int:genre_id>/', views.lesson_genre_edit, name='genre_edit'),  # 修正
]

reports/urls.py
from django.urls import path
from reports import views

app_name = 'reports'
urlpatterns = [
    # レポート
    path('list/', views.get_report, name='list'),   # 一覧
]

sample_app/urls.py
from django.contrib import admin
from django.urls import path, include
from templates import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.index_template, name='index'),
    path('bills/', include('bills.urls')),
    path('customers/', include('customers.urls')),
    path('lessons/', include('lessons.urls')),
    path('reports/', include('reports.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-dark bg-primary">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">サンプル</a>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}
メニュー
{% endblock %}

{% block body %}
<h4 class="mt-4 border-bottom">メニュー</h4>

<a href="{% url 'customers:list' %}" class="btn btn-primary btn-lg btn-block">顧客一覧</a>
<a href="{% url 'lessons:history_list' %}" class="btn btn-primary btn-lg btn-block">レッスン受講記録</a>
<a href="{% url 'bills:list' %}" class="btn btn-primary btn-lg btn-block">月別請求一覧</a>
<a href="{% url 'reports:list' %}" class="btn btn-primary btn-lg btn-block">レポート</a>
<br>
<a href="{% url 'lessons:genre_list' %}" class="btn btn-primary btn-lg btn-block">ジャンル一覧</a>
{% endblock %}