bills/urls.py
from django.urls import path
from bills import views

app_name = 'bills'
urlpatterns = [
    # 請求一覧
    path('list/', views.get_bill_list, name='list'),   # 一覧
]

lessons/urls.py
from django.urls import path
from lessons import views

app_name = 'lessons'
urlpatterns = [
    # レッスン
    path('list/', views.get_lesson_history_list, name='history_list'),   # 一覧
    path('genre_list/', views.get_lesson_genre_list, name='genre_list'),   # 一覧
    path('add/', views.lesson_history_edit, name='history_add'),  # 登録
    path('genre_add/', views.lesson_genre_edit, name='genre_add'),  # 登録
    path('edit/<int:history_id>/', views.lesson_history_edit, name='history_edit'),  # 修正
    path('genre_edit/<int:genre_id>/', views.lesson_genre_edit, name='genre_edit'),  # 修正
]

sample_app/urls.py
from django.contrib import admin
from django.urls import path, include
from templates import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.index_template, name='index'),
    path('bills/', include('bills.urls')),
    path('customers/', include('customers.urls')),
    path('lessons/', include('lessons.urls')),
    path('reports/', include('reports.urls')),
]

lessons/models.py
from django.utils import timezone
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from customers.models import Customer
from lessons.calculate_logics.logics import Logics


class CalculateLogic(models.Model):
    """
    料金計算ロジック
    """
    name = models.CharField(
        verbose_name='計算名称',
        max_length=30,
        unique=True,
    )
    # 料金計算ロジックの関数名を指定する
    logic_name = models.CharField(
        verbose_name='ロジック名称',
        help_text='(入力する値は担当者に要確認)',
        max_length=30,
        unique=True,
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name

    def get_calculate_function(self):
        return Logics().__getattribute__(str(self.logic_name))

class Genre(models.Model):
    """
    受講ジャンル
    """
    name = models.CharField(
        verbose_name='ジャンル名',
        max_length=30,
    )
    calculate_logic = models.ForeignKey(
        CalculateLogic,
        verbose_name='計算方法',
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.name

    def calculate_price(self, hour):
        calculate_function = self.calculate_logic.get_calculate_function()
        return calculate_function(hour)

class History(models.Model):
    """
    受講記録
    """
    customer = models.ForeignKey(
        Customer,
        verbose_name='顧客名',
        on_delete=models.CASCADE,
    )
    lesson_on = models.DateField(
        verbose_name='受講日',
        default=timezone.now().date(),
    )
    lesson_genre = models.ForeignKey(
        Genre,
        verbose_name='ジャンル',
        on_delete=models.CASCADE,
    )
    lesson_hour = models.PositiveSmallIntegerField(
        verbose_name='受講時間(h)',
        validators=[MinValueValidator(1), MaxValueValidator(12)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

lessons/forms.py
from django.forms import ModelForm, DateField, SelectDateWidget
from lessons.models import History, Genre, CalculateLogic


class HistoryForm(ModelForm):
    """
    受講記録フォーム
    """
    lesson_on = DateField(
        label='受講日',
        widget=SelectDateWidget,
    )

    class Meta:
        model = History
        fields = (
            'customer',
            'lesson_genre',
            'lesson_on',
            'lesson_hour',
        )

class GenreForm(ModelForm):
    """
    受講ジャンルフォーム
    """
    class Meta:
        model = Genre
        fields = (
            'name',
            'calculate_logic',
        )

class CalculateLogicForm(ModelForm):
    """
    料金計算ロジックフォーム
    """
    class Meta:
        model = CalculateLogic
        fields = (
            'name',
            'logic_name',
        )

lessons/views.py
from django.shortcuts import render, get_object_or_404, redirect

from lessons.models import History, Genre
from lessons.forms import HistoryForm, GenreForm, CalculateLogicForm
from lessons.calculate_logics.logics import Logics

def get_lesson_history_list(request):
    """
    受講記録一覧を取得する
    """

    histories = History.objects.all().order_by('id')
    for history in histories:
        calculate_function = Logics().__getattribute__(history.lesson_genre.calculate_logic.logic_name)
        lesson_price = calculate_function(history.lesson_hour)
        history.__setattr__('lesson_price', lesson_price)

    return render(request,
                  'lessons/list.html',
                  {'histories': histories},
                  )

def lesson_history_edit(request, history_id=None):
    """
    受講記録を新規作成/編集する
    """

    if history_id:
        history = get_object_or_404(History, pk=history_id)
    else:
        history = History()

    if request.method == 'POST':
        form = HistoryForm(request.POST, instance=history)
        if form.is_valid():
            history = form.save(commit=False)
            history.save()
            return redirect('lessons:history_list')
    else:
        form = HistoryForm(instance=history)

    return render(
        request,
        'lessons/edit.html',
        dict(form=form, history_id=history_id)
    )


def get_lesson_genre_list(request):
    """
    ジャンル一覧を取得する
    :param request:
    :return: lesson_genreのList
    """

    genres = Genre.objects.all().order_by('id')
    return render(request,
                  'lessons/genre_list.html',
                  {'genres': genres},
                  )

def lesson_genre_edit(request, genre_id=None):
    """
    ジャンルを新規作成/編集する
    """

    if genre_id:
        genre = get_object_or_404(Genre, pk=genre_id)
    else:
        genre = Genre()

    if request.method == 'POST':
        form = GenreForm(request.POST, instance=genre)
        if form.is_valid():
            genre = form.save(commit=False)
            genre.save()
            return redirect('lessons:genre_list')
    else:
        form = GenreForm(instance=genre)

    return render(
        request,
        'lessons/genre_edit.html',
        dict(form=form, genre_id=genre_id)
    )

lessons/templates/lessons/edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}
    {% if history_id %}
    レッスン受講記録編集
    {% else %}
    レッスン受講記録登録
    {% endif %}
{% endblock %}

{% block body %}
    {% if history_id %}
    <h4 class="mt-4 mb-5 border-bottom">レッスン受講記録編集</h4>
    <form action="{% url 'lessons:history_edit' history_id=history_id %}" method="post">
    {% else %}
    <h4 class="mt-4 mb-5 border-bottom">レッスン受講記録登録</h4>
    <form action="{% url 'lessons:history_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
{% endblock %}

lessons/templates/lessons/genre_edit.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}
    {% if genre_id %}
    ジャンル編集
    {% else %}
    ジャンル登録
    {% endif %}
{% endblock %}

{% block body %}
    {% if genre_id %}
    <h4 class="mt-4 mb-5 border-bottom">ジャンル編集</h4>
    <form action="{% url 'lessons:genre_edit' genre_id=genre_id %}" method="post">
    {% else %}
    <h4 class="mt-4 mb-5 border-bottom">ジャンル登録</h4>
    <form action="{% url 'lessons:genre_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">登録</button>
        </div>
      </div>
    </form>
{% endblock %}

lessons/templates/lessons/genre_list.html
{% extends "base.html" %}

{% block title %}
レッスンジャンル一覧
{% endblock %}

{% block body %}
<h4 class="mt-4 border-bottom">レッスンジャンル一覧</h4>
<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">ジャンル名</th>
      <th scope="col">計算方法</th>
    </tr>
  </thead>
  <tbody>
    {% for genre in genres %}
    <tr>
      <th scope="row">{{ genre.id }}</th>
      <td>{{ genre.name }}</td>
      <td>{{ genre.calculate_logic }}</td>
      <td>
        <a href="{% url 'lessons:genre_edit' genre_id=genre.id %}" class="btn btn-outline-primary btn-sm">編集</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'lessons:genre_add' %}" class="btn btn-primary btn-sm my-3">新規追加</a>
{% endblock %}

lessons/templates/lessons/list.html
{% extends "base.html" %}

{% block title %}
レッスン受講記録一覧
{% endblock %}

{% block body %}
<h4 class="mt-4 border-bottom">レッスン受講記録一覧</h4>
<table class="table table-sm table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">受講者</th>
      <th scope="col">ジャンル</th>
      <th scope="col">受講日</th>
      <th scope="col">受講時間</th>
      <th scope="col">支払い金額<br>(日毎の受講時間より計算)</th>
    </tr>
  </thead>
  <tbody>
    {% for history in histories %}
    <tr>
      <th scope="row">{{ history.id }}</th>
      <td>{{ history.customer.name }}</td>
      <td>{{ history.lesson_genre }}</td>
      <td>{{ history.lesson_on }}</td>
      <td>{{ history.lesson_hour }} h</td>
      <td>{{ history.lesson_price }} 円</td>
      <td>
        <a href="{% url 'lessons:history_edit' history_id=history.id %}" class="btn btn-outline-primary btn-sm">編集</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'lessons:history_add' %}" class="btn btn-primary btn-sm my-3">新規追加</a>
{% endblock %}